### ISSUE TITLE
git clone error

### ISSUE THREAD

**Issue by KangKyungSoo** [gismo141/laserIMUCalibration#3]
I met following error, when I tried to do 'git clone', I am using Ubuntu 16.04.

> git clone git@github.com:gismo141/laserIMUCalibration 
> Cloning into 'laserIMUCalibration'...
> Permission denied (publickey).
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.

**Comment by gismo141** [comment]
Sorry for that inconvenience, I've changed the `git clone` command accordingly.
